// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnjacehtzetkmpzsembn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuamFjZWh0emV0a21wenNlbWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjY4NTEsImV4cCI6MjA2OTQ0Mjg1MX0.FUUcl-jDijVUoJj1kxVMqTwF9y6furnrprtNTvlemdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});